DROP DATABASE IF EXISTS UCI;
CREATE DATABASE UCI;
USE UCI;

/* Tablas */

DROP TABLE IF EXISTS `PATIENTS`;
CREATE TABLE IF NOT EXISTS `PATIENTS`(
    `ROW_ID` INT NOT NULL,
    `SUBJECT_ID` INT NOT NULL,
    `GENDER` VARCHAR(5) NOT NULL,
    `DOB` DATETIME NOT NULL,
    `DOD` DATETIME ,
    `DOD_HOSP` DATETIME ,
    `DOD_SSN` DATETIME ,
    `EXPIRE_FLAG` VARCHAR(5) NOT NULL,
    /*`DOB_HR` FLOAT(15),
    `DOD_HR` FLOAT(15),*/
    `AGE` FLOAT(15),
    PRIMARY KEY (`SUBJECT_ID`)
);

DROP TABLE IF EXISTS `D_ITEMS`;
CREATE TABLE IF NOT EXISTS `D_ITEMS`(
    `ROW_ID` INT NOT NULL,
    `ITEMID` INT NOT NULL,
    `LABEL` VARCHAR(200) ,
    `ABBREVIATION` VARCHAR(100) ,
    `DBSOURCE` VARCHAR(20) NOT NULL,
    `LINKSTO` VARCHAR(50) ,
    `CATEGORY` VARCHAR(100) ,
    `UNITNAME` VARCHAR(100) ,
    `PARAM_TYPE` VARCHAR(30) ,
    PRIMARY KEY (`ITEMID`)
);

DROP TABLE IF EXISTS `D_LABITEMS`;
CREATE TABLE IF NOT EXISTS `D_LABITEMS`(
    `ROW_ID` INT NOT NULL,
    `ITEMID` INT NOT NULL,
    `LABEL` VARCHAR(100) NOT NULL,
    `FLUID` VARCHAR(100) NOT NULL,
    `CATEGORY` VARCHAR(100) NOT NULL,
    `LOINC_CODE` VARCHAR(100) ,
    PRIMARY KEY (`ITEMID`)
);

DROP TABLE IF EXISTS `D_CPT`;
CREATE TABLE IF NOT EXISTS `D_CPT`(
    `ROW_ID` INT NOT NULL,
    `CATEGORY` SMALLINT NOT NULL,
    `SECTIONRANGE` VARCHAR(100) NOT NULL,
    `SECTIONHEADER` VARCHAR(50) NOT NULL,
    `SUBSECTIONRANGE` VARCHAR(100) NOT NULL,
    `SUBSECTIONHEADER` VARCHAR(300) NOT NULL,
    `MINCODEINSUBSECTION` INT NOT NULL,
    `MAXCODEINSUBSECTION` INT NOT NULL,
    PRIMARY KEY (`ROW_ID`)
);

DROP TABLE IF EXISTS `D_ICD_DIAGNOSES`;
CREATE TABLE IF NOT EXISTS `D_ICD_DIAGNOSES`(
    `ROW_ID` INT NOT NULL,
    `ICD9_CODE` VARCHAR(10) NOT NULL,
    `SHORT_TITLE` VARCHAR(50) NOT NULL,
    `LONG_TITLE` VARCHAR(300) NOT NULL,
    `SUPER_CATEGORY` VARCHAR(30),
    PRIMARY KEY (`ICD9_CODE`)
);

DROP TABLE IF EXISTS `D_ICD_PROCEDURES`;
CREATE TABLE IF NOT EXISTS `D_ICD_PROCEDURES`(
    `ROW_ID` INT NOT NULL,
    `ICD9_CODE` VARCHAR(10) NOT NULL,
    `SHORT_TITLE` VARCHAR(50) NOT NULL,
    `LONG_TITLE` VARCHAR(300) NOT NULL,
    PRIMARY KEY (`ROW_ID`)
);

DROP TABLE IF EXISTS `CAREGIVERS`;
CREATE TABLE IF NOT EXISTS `CAREGIVERS`(
    `ROW_ID` INT NOT NULL,
    `CGID` INT NOT NULL,
    `LABEL` VARCHAR(15),
    `DESCRIPTION` VARCHAR(30),
    PRIMARY KEY (`CGID`)
);

DROP TABLE IF EXISTS `ADMISSIONS`;
CREATE TABLE IF NOT EXISTS `ADMISSIONS` (
	`ROW_ID` INT UNIQUE NOT NULL,
	`SUBJECT_ID` INT NOT NULL,
	`HADM_ID` INT NOT NULL,
	`ADMITTIME`  DATETIME NOT NULL,
	`DISCHTIME` DATETIME NOT NULL,
	`DEATHTIME` DATETIME,
	`ADMISSION_TYPE` VARCHAR(50) NOT NULL,
	`ADMISSION_LOCATION` VARCHAR(50) NOT NULL,
	`DISCHARGE_LOCATION` VARCHAR(50)  NOT NULL,
	`INSURANCE` VARCHAR(255) NOT NULL,
	`LANGUAGE` VARCHAR(10),
	`RELIGION` VARCHAR(50),
	`MARITAL_STATUS` VARCHAR(50),
	`ETHNICITY` VARCHAR(200) NOT NULL,
	`EDREGTIME` DATETIME,
	`EDOUTTIME` DATETIME,
	`DIAGNOSIS` VARCHAR(300),
	`HOSPITAL_EXPIRE_FLAG` TINYINT NOT NULL,
	`HAS_CHARTEVENTS_DATA` TINYINT NOT NULL,
    `DIED_AT_THE_HOSPITAL` INT,
	PRIMARY KEY (`HADM_ID`),
	FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS`(`SUBJECT_ID`)
);

DROP TABLE IF EXISTS `ICUSTAYS`;
CREATE TABLE IF NOT EXISTS `ICUSTAYS`(
    `ROW_ID` INT NOT NULL,
    `SUBJECT_ID` INT NOT NULL,
    `HADM_ID` INT NOT NULL,
    `ICUSTAY_ID` INT NOT NULL,
    `DBSOURCE` VARCHAR(20) NOT NULL,
    `FIRST_CAREUNIT` VARCHAR(20) NOT NULL,
    `LAST_CAREUNIT` VARCHAR(20) NOT NULL,
    `FIRST_WARDID` SMALLINT NOT NULL,
    `LAST_WARDID` SMALLINT NOT NULL,
    `INTIME` DATETIME NOT NULL,
    `OUTTIME` DATETIME ,
    `LOS` FLOAT(15) ,
    PRIMARY KEY (`ICUSTAY_ID`),
    FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS`(`SUBJECT_ID`),
    FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS`(`HADM_ID`)
);
                                        
DROP TABLE IF EXISTS `CALLOUT`;
CREATE TABLE IF NOT EXISTS `CALLOUT`(
    `ROW_ID` INT NOT NULL,
    `SUBJECT_ID` INT NOT NULL,
    `HADM_ID` INT NOT NULL,
    `SUBMIT_WARDID` INT,
    `SUBMIT_CAREUNIT` VARCHAR(15) ,
    `CURR_WARDID` INT,
    `CURR_CAREUNIT` VARCHAR(15) ,
    `CALLOUT_WARDID` INT NOT NULL,
    `CALLOUT_SERVICE` VARCHAR(10) NOT NULL,
    `REQUEST_TELE` SMALLINT NOT NULL,
    `REQUEST_RESP` SMALLINT NOT NULL,
    `REQUEST_CDIFF` SMALLINT NOT NULL,
    `REQUEST_MRSA` SMALLINT NOT NULL,
    `REQUEST_VRE` SMALLINT NOT NULL,
    `CALLOUT_STATUS` VARCHAR(20) NOT NULL,
    `CALLOUT_OUTCOME` VARCHAR(20) NOT NULL,
    `DISCHARGE_WARDID` INT,
    `ACKNOWLEDGE_STATUS` VARCHAR(20) NOT NULL,
    `CREATETIME` DATETIME NOT NULL,
    `UPDATETIME` DATETIME NOT NULL,
    `ACKNOWLEDGETIME` DATETIME,
    `OUTCOMETIME` DATETIME NOT NULL,
    `FIRSTRESERVATIONTIME` DATETIME,
    `CURRENTRESERVATIONTIME` DATETIME,
    PRIMARY KEY (`ROW_ID`),
    FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS`(`SUBJECT_ID`),
    FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS`(`HADM_ID`)
);

DROP TABLE IF EXISTS `CHARTEVENTS`;
CREATE TABLE IF NOT EXISTS `CHARTEVENTS`(
    `ROW_ID` INT NOT NULL,
    `SUBJECT_ID` INT NOT NULL,
    `HADM_ID` INT ,
    `ICUSTAY_ID` INT ,
    `ITEMID` INT NOT NULL,
    `CHARTTIME` DATETIME NOT NULL,
    `STORETIME` DATETIME ,
    `CGID` INT ,
    `VALUENUM` INT ,
    `VALUEUOM` VARCHAR(20) ,
    `WARNING` INT ,
    `ERROR` INT ,
    `RESULTSTATUS` VARCHAR(20) ,
    `STOPPED` VARCHAR(20) ,
    PRIMARY KEY (`ROW_ID`),
    FOREIGN KEY (`ITEMID`) REFERENCES `D_ITEMS`(`ITEMID`),
    FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS`(`HADM_ID`),
    FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS`(`SUBJECT_ID`)
);

DROP TABLE IF EXISTS `CPTEVENTS`;
CREATE TABLE IF NOT EXISTS `CPTEVENTS`(
    `ROW_ID` INT NOT NULL,
    `SUBJECT_ID` INT NOT NULL,
    `HADM_ID` INT NOT NULL,
    `COSTCENTER` VARCHAR(10) NOT NULL,
    `CHARTDATE` DATETIME ,
    `CPT_CD` VARCHAR(10) ,
    `CPT_NUMBER` INT ,
    `TICKET_ID_SEQ` INT ,
    `SECTIONHEADER` VARCHAR(50) ,
    `SUBSECTIONHEADER` VARCHAR(300) ,
    `DESCRIPTION` VARCHAR(200) ,
    PRIMARY KEY (`ROW_ID`),
    FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS`(`SUBJECT_ID`),
    FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS`(`HADM_ID`)
);

DROP TABLE IF EXISTS `DATETIMEEVENTS`;
CREATE TABLE IF NOT EXISTS `DATETIMEEVENTS`(
    `ROW_ID` INT NOT NULL,
    `SUBJECT_ID` INT NOT NULL,
    `HADM_ID` INT ,
    `ICUSTAY_ID` INT ,
    `ITEMID` INT NOT NULL,
    `CHARTTIME` DATETIME NOT NULL,
    `STORETIME` DATETIME NOT NULL,
    `CGID` INT NOT NULL,
    `VALUE` DATETIME,
    `VALUEUOM` VARCHAR(50) NOT NULL,
    `WARNING` SMALLINT ,
    `ERROR` SMALLINT ,
    `STOPPED` VARCHAR(50) ,
    PRIMARY KEY (`ROW_ID`),
    FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS`(`SUBJECT_ID`),
    FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS`(`HADM_ID`),
    FOREIGN KEY (`ITEMID`) REFERENCES `D_ITEMS`(`ITEMID`),
    FOREIGN KEY (`CGID`) REFERENCES `CAREGIVERS`(`CGID`)
);

DROP TABLE IF EXISTS `DIAGNOSES_ICD`;
CREATE TABLE IF NOT EXISTS `DIAGNOSES_ICD`(
    `ROW_ID` INT NOT NULL,
    `SUBJECT_ID` INT NOT NULL,
    `HADM_ID` INT NOT NULL,
    `SEQ_NUM` INT ,
    `ICD9_CODE` VARCHAR(10) ,
    PRIMARY KEY (`ROW_ID`),
    FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS`(`SUBJECT_ID`), 
    FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS`(`HADM_ID`)
);

DROP TABLE IF EXISTS `DRGCODES`;
CREATE TABLE IF NOT EXISTS `DRGCODES`(
    `ROW_ID` INT NOT NULL,
    `SUBJECT_ID` INT NOT NULL,
    `HADM_ID` INT NOT NULL,
    `DRG_TYPE` VARCHAR(20) NOT NULL,
    `DRG_CODE` VARCHAR(20) NOT NULL,
    `DESCRIPTION` VARCHAR(300) ,
    `DRG_SEVERITY` SMALLINT ,
    `DRG_MORTALITY` SMALLINT ,
    PRIMARY KEY (`ROW_ID`),
    FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS`(`SUBJECT_ID`),
    FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS`(`HADM_ID`)
);

DROP TABLE IF EXISTS `INPUTEVENTS_CV`;
CREATE TABLE IF NOT EXISTS `INPUTEVENTS_CV`(
    `ROW_ID` INT NOT NULL,
    `SUBJECT_ID` INT NOT NULL,
    `HADM_ID` INT ,
    `ICUSTAY_ID` INT ,
    `CHARTTIME` DATETIME NOT NULL,
    `ITEMID` INT NOT NULL,
    `AMOUNT` FLOAT(15) ,
    `AMOUNTUOM` VARCHAR(30) ,
    `STORETIME` DATETIME NOT NULL,
    `CGID` INT ,
    `ORDERID` BIGINT NOT NULL,
    `LINKORDERID` BIGINT NOT NULL,
    `ORIGINALAMOUNT` FLOAT(15) ,
    `ORIGINALAMOUNTUOM` VARCHAR(30) ,
    `ORIGINALROUTE` VARCHAR(30) ,
    PRIMARY KEY (`ROW_ID`),
    FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS`(`SUBJECT_ID`),
    FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS`(`HADM_ID`),
    FOREIGN KEY (`ICUSTAY_ID`) REFERENCES `ICUSTAYS`(`ICUSTAY_ID`),
    FOREIGN KEY (`ITEMID`) REFERENCES `D_ITEMS`(`ITEMID`)
);

DROP TABLE IF EXISTS `INPUTEVENTS_MV`;
CREATE TABLE IF NOT EXISTS `INPUTEVENTS_MV`(
    `ROW_ID` INT NOT NULL,
    `SUBJECT_ID` INT NOT NULL,
    `HADM_ID` INT NOT NULL,
    `ICUSTAY_ID` INT , 
    `STARTTIME` DATETIME NOT NULL,
    `ENDTIME` DATETIME NOT NULL,
    `ITEMID` INT NOT NULL, 
    `AMOUNT` FLOAT(15) NOT NULL, 
    `AMOUNTUOM` VARCHAR(30) NOT NULL,
    `RATE` FLOAT(15) ,
    `RATEUOM` VARCHAR(30) ,
    `STORETIME` DATETIME NOT NULL,
    `CGID` INT NOT NULL,
    `ORDERID` BIGINT NOT NULL,
    `LINKORDERID` BIGINT NOT NULL, 
    `ORDERCATEGORYNAME` VARCHAR(100) NOT NULL,
    `SECONDARYORDERCATEGORYNAME` VARCHAR(100) ,
    `ORDERCOMPONENTTYPEDESCRIPTION` VARCHAR(200) NOT NULL,
    `ORDERCATEGORYDESCRIPTION` VARCHAR(50) NOT NULL,
    `PATIENTWEIGHT` FLOAT(15) NOT NULL,
    `TOTALAMOUNT` FLOAT(15) , 
    `TOTALAMOUNTUOM` VARCHAR(50) ,
    `ISOPENBAG` SMALLINT NOT NULL,
    `CONTINUEINNEXTDEPT` SMALLINT NOT NULL,
    `CANCELREASON` SMALLINT NOT NULL, 
    `STATUSDESCRIPTION` VARCHAR(30) NOT NULL,
    `COMMENTS_EDITEDBY` VARCHAR(30) ,
    `ORIGINALAMOUNT` FLOAT(15) NOT NULL,
    `ORIGINALRATE` FLOAT(15) NOT NULL,
    PRIMARY KEY (`ROW_ID`),
    FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS`(`SUBJECT_ID`),
    FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS`(`HADM_ID`),
    FOREIGN KEY (`ICUSTAY_ID`) REFERENCES `ICUSTAYS`(`ICUSTAY_ID`),
    FOREIGN KEY (`ITEMID`) REFERENCES `D_ITEMS`(`ITEMID`),
    FOREIGN KEY (`CGID`) REFERENCES `CAREGIVERS`(`CGID`)
);

DROP TABLE IF EXISTS `LABEVENTS`;
CREATE TABLE IF NOT EXISTS `LABEVENTS`(
    `ROW_ID` INT NOT NULL,
    `SUBJECT_ID` INT NOT NULL,
    `HADM_ID` INT ,
    `ITEMID` INT NOT NULL,
    `CHARTTIME` DATETIME NOT NULL,
    `VALUENUM` FLOAT(15) ,
    `VALUEUOM` VARCHAR(20) ,
    `FLAG` VARCHAR(20) ,
    PRIMARY KEY (`ROW_ID`),
    FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS`(`SUBJECT_ID`),
    FOREIGN KEY (`ITEMID`) REFERENCES `D_LABITEMS`(`ITEMID`)
);

DROP TABLE IF EXISTS `MICROBIOLOGYEVENTS`;
CREATE TABLE IF NOT EXISTS `MICROBIOLOGYEVENTS`(
    `ROW_ID` INT NOT NULL,
    `SUBJECT_ID` INT NOT NULL,
    `HADM_ID` INT ,
    `CHARTDATE` DATETIME NOT NULL,
    `CHARTTIME` DATETIME ,
    `SPEC_ITEMID` INT ,
    `SPEC_TYPE_DESC` VARCHAR(100) NOT NULL,
    `ORG_ITEMID` INT ,
    `ORG_NAME` VARCHAR(100) ,
    `ISOLATE_NUM` SMALLINT ,
    `AB_ITEMID` INT ,
    `AB_NAME` VARCHAR(30) ,
    `DILUTION_TEXT` VARCHAR(10) ,
    `DILUTION_COMPARISON` VARCHAR(20) ,
    `DILUTION_VALUE` FLOAT(15) ,
    `INTERPRETATION` VARCHAR(5) ,
    PRIMARY KEY (`ROW_ID`),
    FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS`(`SUBJECT_ID`),
    FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS`(`HADM_ID`),
    FOREIGN KEY (`SPEC_ITEMID`) REFERENCES `D_ITEMS`(`ITEMID`)
);

DROP TABLE IF EXISTS `OUTPUTEVENTS`;
CREATE TABLE IF NOT EXISTS `OUTPUTEVENTS`(
    `ROW_ID` INT NOT NULL,
    `SUBJECT_ID` INT NOT NULL,
    `HADM_ID` INT ,
    `ICUSTAY_ID` INT ,
    `CHARTTIME` DATETIME NOT NULL,
    `ITEMID` INT NOT NULL,
    `VALUE` FLOAT(15) ,
    `VALUEUOM` VARCHAR(30) ,
    `STORETIME` DATETIME NOT NULL,
    `CGID` INT NOT NULL,
    PRIMARY KEY (`ROW_ID`),
    FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS`(`SUBJECT_ID`),
    FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS`(`HADM_ID`),
    FOREIGN KEY (`ITEMID`) REFERENCES `D_ITEMS`(`ITEMID`),
    FOREIGN KEY (`CGID`) REFERENCES `CAREGIVERS`(`CGID`)
);
                                        
DROP TABLE IF EXISTS `PRESCRIPTIONS`;
CREATE TABLE IF NOT EXISTS `PRESCRIPTIONS`(
    `ROW_ID` INT NOT NULL,
    `SUBJECT_ID` INT NOT NULL,
    `HADM_ID` INT NOT NULL,
    `ICUSTAY_ID` INT ,
    `STARTDATE` DATETIME ,
    `ENDDATE` DATETIME ,
    `DRUG_TYPE` VARCHAR(100) NOT NULL,
    `DRUG` VARCHAR(100) NOT NULL,
    `DRUG_NAME_POE` VARCHAR(100) ,
    `DRUG_NAME_GENERIC` VARCHAR(100) ,
    `FORMULARY_DRUG_CD` VARCHAR(120) ,
    `GSN` VARCHAR(200) ,
    `NDC` VARCHAR(120) ,
    `PROD_STRENGTH` VARCHAR(120) ,
    `DOSE_VAL_RX` VARCHAR(120) ,
    `DOSE_UNIT_RX` VARCHAR(120) ,
    `FORM_VAL_DISP` VARCHAR(120) ,
    `FORM_UNIT_DISP` VARCHAR(120) ,
    `ROUTE` VARCHAR(120) ,
    PRIMARY KEY (`ROW_ID`),
    FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS`(`SUBJECT_ID`),
    FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS`(`HADM_ID`)
);                  

DROP TABLE IF EXISTS `PROCEDUREEVENTS_MV`;
CREATE TABLE IF NOT EXISTS `PROCEDUREEVENTS_MV`(
    `ROW_ID` INT NOT NULL,
    `SUBJECT_ID` INT NOT NULL,
    `HADM_ID` INT NOT NULL,
    `ICUSTAY_ID` INT NOT NULL,
    `STARTTIME` DATETIME NOT NULL,
    `ENDTIME` DATETIME NOT NULL,
    `ITEMID` INT NOT NULL,
    `VALUE` FLOAT(15) NOT NULL,
    `VALUEUOM` VARCHAR(30) NOT NULL,
    `STORETIME` DATETIME NOT NULL,
    `CGID` INT NOT NULL,
    `ORDERID` INT NOT NULL,
    `LINKORDERID` INT NOT NULL,
    `ORDERCATEGORYNAME` VARCHAR(100) NOT NULL,
    `ORDERCATEGORYDESCRIPTION` VARCHAR(50) NOT NULL,
    `ISOPENBAG` SMALLINT NOT NULL,
    `CONTINUEINNEXTDEPT` SMALLINT NOT NULL,
    `CANCELREASON` SMALLINT NOT NULL,
    `STATUSDESCRIPTION` VARCHAR(30) NOT NULL,
    PRIMARY KEY (`ORDERID`),
    FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS`(`SUBJECT_ID`),
    FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS`(`HADM_ID`),
    FOREIGN KEY (`ICUSTAY_ID`) REFERENCES `ICUSTAYS`(`ICUSTAY_ID`),
    FOREIGN KEY (`ITEMID`) REFERENCES `D_ITEMS`(`ITEMID`),
    FOREIGN KEY (`CGID`) REFERENCES `CAREGIVERS`(`CGID`)
);

DROP TABLE IF EXISTS `PROCEDURES_ICD`;
CREATE TABLE IF NOT EXISTS `PROCEDURES_ICD`(
    `ROW_ID` INT NOT NULL,
    `SUBJECT_ID` INT NOT NULL,
    `HADM_ID` INT NOT NULL,
    `SEQ_NUM` INT NOT NULL,
    `ICD9_CODE` VARCHAR(10) NOT NULL,
    PRIMARY KEY (`ROW_ID`),
    FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS`(`SUBJECT_ID`),
    FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS`(`HADM_ID`)
);

DROP TABLE IF EXISTS `SERVICES`;
CREATE TABLE IF NOT EXISTS `SERVICES`(
    `ROW_ID` INT NOT NULL,
    `SUBJECT_ID` INT NOT NULL,
    `HADM_ID` INT NOT NULL,
    `TRANSFERTIME` DATETIME NOT NULL,
    `PREV_SERVICE` VARCHAR(20) ,
    `CURR_SERVICE` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`ROW_ID`),
    FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS`(`SUBJECT_ID`),
    FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS`(`HADM_ID`)
);

DROP TABLE IF EXISTS `TRANSFERS`;
CREATE TABLE IF NOT EXISTS `TRANSFERS`(
    `ROW_ID` INT NOT NULL,
    `SUBJECT_ID` INT NOT NULL,
    `HADM_ID` INT NOT NULL,
    `ICUSTAY_ID` INT ,
    `DBSOURCE` VARCHAR(20) ,
    `EVENTTYPE` VARCHAR(20) ,
    `PREV_CAREUNIT` VARCHAR(20) ,
    `CURR_CAREUNIT` VARCHAR(20) ,
    `PREV_WARDID` SMALLINT ,
    `CURR_WARDID` SMALLINT ,
    `INTIME` DATETIME,
    `OUTTIME` DATETIME,
    `LOS` INT ,
    PRIMARY KEY (`ROW_ID`),
    FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS`(`SUBJECT_ID`),
    FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS`(`HADM_ID`)
);                    
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        